ap:
  build: .
  command: /bin/bash -c "rails server -b 0.0.0.0"
  volumes:
    - '.:/usr/src/app'
  ports:
    - "3000:3000"
  expose:
    - "3000"
  environment:
    - RAILS_ENV=production
    - RAILS_SERVE_STATIC_FILES
    - FIRST_STORE_DATABASE_HOST
    - FIRST_STORE_DATABASE_USER
    - FIRST_STORE_DATABASE_PASSWORD
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - S3_BUCKET_NAME
    - S3_HOST_NAME
    - APP_URL_OPTIONS_HOST
    - APP_URL_OPTIONS_PORT
    - APP_URL_OPTIONS_PROTOCOL
    - SECRET_KEY_BASE
    - BUNDLE_APP_CONFIG=.bundle
    - BUNDLE_CLEAN=true
    - APP_MAIL_OPTIONS_MAILS_FROM
    - APP_MAIL_OPTIONS_ENABLE_MAIL_DELIVERY
    - APP_MAIL_OPTIONS_MAIL_BCC
    - APP_MAIL_OPTIONS_INTERCEPT_EMAIL
    - APP_MAIL_OPTIONS_MAIL_HOST
    - APP_MAIL_OPTIONS_MAIL_DOMAIN
    - APP_MAIL_OPTIONS_MAIL_PORT
    - APP_MAIL_OPTIONS_SECURE_CONNECTION_TYPE
    - APP_MAIL_OPTIONS_MAIL_AUTH_TYPE
    - APP_MAIL_OPTIONS_SMTP_USERNAME
    - APP_MAIL_OPTIONS_SMTP_PASSWORD

web:
  build: middleware/nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - './public:/usr/local/var/www'
  links:
    - ap
