ap:
  build: .
  command: /bin/bash -c "rake db:migrate:reset db:seed && rake spree_sample:load assets:precompile && rails server -b 0.0.0.0"
  ports:
    - "3000:3000"
  expose:
   - "3000"
  environment:
    - RAILS_ENV=production
    - AUTO_ACCEPT=true
    - RAILS_SERVE_STATIC_FILES=true
    - FIRST_STORE_DATABASE_HOST
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - S3_BUCKET_NAME
    - S3_HOST_NAME
    - SECRET_KEY_BASE=3e2ddf71c1c5651331b9c805b5ecf2290b60a37d5220ee4326312d959cafbffc62616c9696ddfff528309995d038d77a560f08444b571dd322061af4bdeb1f87
