db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root

web:
  build: .
  command: rails server -b 0.0.0.0
  ports:
    - '3000:3000'
  volumes:
    - '.:/usr/src/app'
  links:
    - db
  environment:
    - RAILS_ENV=demo
