db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root

ap:
  build: .
  command: /bin/bash -c "sleep 15 && rake railties:install:migrations db:migrate:reset db:seed && rake spree_sample:load assets:precompile && rails server -b 0.0.0.0"
  ports:
    - "3000:3000"
  expose:
   - "3000"
  links:
    - db
  environment:
    - RAILS_ENV=demo
    - AUTO_ACCEPT=true
    - RAILS_SERVE_STATIC_FILES=true
    - SECRET_KEY_BASE=3e2ddf71c1c5651331b9c805b5ecf2290b60a37d5220ee4326312d959cafbffc62616c9696ddfff528309995d038d77a560f08444b571dd322061af4bdeb1f87
