db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root

web:
  build: .
  command: /bin/bash -c "sleep 10 && rake railties:install:migrations db:migrate:reset db:seed && rake spree_sample:load && rails server -b 0.0.0.0"
  ports:
    - "3000:3000"
  expose:
   - "3000"
  volumes:
    - '.:/usr/src/app'
  links:
    - db
  environment:
    - RAILS_ENV=demo
    - AUTO_ACCEPT=true
